name: svelte-formly

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Restore cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm
        restore-keys: |
          ${{ runner.OS }}-npm
    
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

    - name: Publish to npm
      uses: pascalgn/npm-publish-action@1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}